### ISSUE TITLE
Prepared statements support

### ISSUE THREAD

**Issue by prettynatty** [websudos/phantom#123]
Are there any plans to support prepared statements?
Now I am using my own abstraction. Besides simple prepared statements it allows to choose execution context for a `Future`.
``` scala
abstract class ExecutablePreparedStatement(implicit val session: Session, context: ExecutionContext with Executor) {
  val query: String

  private lazy val statement = session.prepare(query)

  def execute(values: java.lang.Object*): Future[ResultSet] = {
    val bs = new BoundStatement(statement).bind(values: _*)
    statementToFuture(bs)
  }

  private def statementToFuture(s: Statement)(implicit session: Session): ScalaFuture[ResultSet] = {
    val promise = ScalaPromise[ResultSet]()

    val future = session.executeAsync(s)

    val callback = new FutureCallback[ResultSet] {
      def onSuccess(result: ResultSet): Unit = {
        promise success result
      }

      def onFailure(err: Throwable): Unit = {
        promise failure err
      }
    }

    Futures.addCallback(future, callback, context)

    promise.future
  }
}
```

**Comment by graph1zzlle** [comment]
Hey there !

Any update on this ?

**Comment by alexflav23** [comment]
@graph1zzlle Not yet, we will work to get prepared statements out as soon as we can, they've now hit the top of the todo list.

**Comment by graph1zzlle** [comment]
Great :+1: Thanks for this awesome lib

**Comment by raam86** [comment]
Is there anything the community can do to expedite this?

**Comment by alexflav23** [comment]
Hi @graph1zzlle , @raam86 @prettynatty ,

Spark support is finally coming, with a completely typesafe approach and even automated conversions and Spark SQL support via one of other projects called `morpheus`, a reactive type safe client for SQL databases.

However, as the amount of work and support required to make that a reality is absolutely gargantuan, it will not be part of an open source release and it will be available for purchase starting with mid September of this year.

Outside of full support for Spark & Spark SQL you will also get automated schema migrations, autotables generated on the fly directly from annotated case classes which also generate all possible queries for a schema, and so on.

I will now close this ticket as it's no longer relevant to the open source version of phantom but the underlying issue is now being resolved through the commercial version of phantom.

Regards.

**Comment by graph1zzlle** [comment]
I don't get why prepared statement should be related to Spark

**Comment by velvia** [comment]
I don't understand either.  The value prop of Spark support and migrations is understandable but has nothing to do with prepared statements.  Adding prepared statement support will encourage folks to stay with Phantom for performance. Those that want Spark support can then pay up.  

Another thing I'd encourage you guys to think about is that Datastax has their own Spark connector, and when Datastax is pushing that connector as the official one, it can be difficult to go against that.

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by alexflav23** [comment]
Hi @velvia, @graph1zzlle,

I meant to comment on the other issue, regarding Spark support. My sincere apologies, prepared statements are in the making and will be available open source.

With regards to Spark support, internally we will still use most of the Spark connector to get things done, we will just make it properly typesafe and powerful in Scala. The official one is very clumsy to use and quite poor for a typesafe language with a compiler this powerful.

Regards,
Flavian

**Comment by graph1zzlle** [comment]
Thanks for the informations @alexflav23

**Comment by jknight12882** [comment]
Any word on when this will be available?

**Comment by alexflav23** [comment]
Hi @jknight12882,

The implementation is complete, we are in the final stages of releasing prepared statements and a pull request is already available for them. I think a maximum of 2 weeks and we should see phantom 2.0 out at last.

Regards.

**Comment by alexflav23** [comment]
HI @jknight12882 , @graph1zzlle ,@raam86, @velvia ,

Prepared statements are now live as of phantom `1.14.1`. You can use them with the complementary methods `p_where` and `p_and` or `p_value` inside inserts. Examples are available [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/prepared/PreparedInsertQueryTest.scala) and [here](https://github.com/websudos/phantom/blob/develop/phantom-dsl/src/test/scala/com/websudos/phantom/builder/query/prepared/PreparedSelectQueryTest.scala).

Please consider support of prepared statements experimental at this stage and some bugs or missing features are well expected.

For binding a single argument, there's an implicit `.tp` or `.tuple` method that you can call on any object and that you will need to use when calling `bind(obj)` with a single argument. This is because of an auto-tupling limitation whereby the compiler will not auto-tuple single argument calls. Auto-tupling is used together with Shapeless Generics and Hlists to enable type-safe binds.


Regards.

**Comment by raam86** [comment]
@alexflav23 nice addon. Will update

**Comment by alexflav23** [comment]
Hi @raam86,

Please open separate issues if need be, I'd like to close this one as it will be easier to manage things individually.

**Comment by lahirug** [comment]
Can you please support prepare insert for a Seq, if I have large number of rows to insert I have to bind them for each tuple (Please correct me if I am wrong), and gather each future return from bind. Is there a better way to do bulk insert ?

**Comment by alexflav23** [comment]
HI @lahirug, 

There is a way to do batch inserts, however it is not currently possible to bind from collections. We may address that in the future. One of the best parts of phantom binds is typesafety, so we need to make sure that will be unharmed by introducing a container type.

I'll add a ticket for this internally and keep you posted, meanwhile `Future.sequence` will always be faster performance wise than batch inserts.

Regards,
Flavian

**Comment by alexflav23** [comment]
Also, this doesn't look very difficult.

`val insertions = Future.sequence(seq.map (item => query.bind(item).future()))`. I'm assuming here inside the sequence all the elements already have the correct tuple type expected by the bind. Otherwise, very much a one liner anyway.

This is all off the top of my head, so please let me know if I am missing anything at all.

Regards,
Flavian

**Comment by lahirug** [comment]
@alexflav23 Thanks for the response, that sounds reasonable to have one future for the set.

**Comment by lahirug** [comment]
I have my own column type defined and looks like bind is failing for those. Can you please advice on how should I deal with it.
