### ISSUE TITLE
Spark Integration

### ISSUE THREAD

**Issue by ezhulenev** [websudos/phantom#139]
What is the state of spark integration, I can't find any branch related to spark so I make assumption that it's not started yet.

I'm playing with spark, datastax spark connector and phantom in the same project, and I feel that I understand what I really need. I there is no branch to pick up, I'll try to submit basic proof-of-concept this week.

**Comment by alexflav23** [comment]
@ezhulenev It's been a long time since we kept postponing this and it's about to reach prime time very shortly. Hopefully in April spark integration will become a top priority for phantom. Our attention and time are unfortunately limited resources and yet we see great benefit in having something like ```phantom-spark``` out there. We will keep you posted on how things go.

**Comment by kareblak** [comment]
@alexflav23 Any news on the Spark integration, and will it be trivial for this to work with spark-streaming aswell?

**Comment by alexflav23** [comment]
Hi @kareblak, @ezhulenev,

Spark support is finally coming, with a completely typesafe approach and even automated conversions and Spark SQL support via one of our other projects called `morpheus`, our reactive type safe client for SQL databases.(not yet open source and live).

However, as the amount of work and support required to make that a reality is absolutely gargantuan, it will not be part of an open source release and it will be available for purchase starting for a small monthly subscription with mid September of this year.

Outside of full support for Spark & Spark SQL you will also get automated schema migrations, a schema migration DSL, a data migration DSL, autotables generated on the fly directly from annotated case classes which also generate all possible queries for a schema, and so on.

I will now close this ticket as it's no longer relevant to the open source version of phantom but the underlying issue is now being resolved through the commercial version of phantom.

Regards.
