### ISSUE TITLE
CassandraStateManager.cassandraRunning returns false positive in some cases

### ISSUE THREAD

**Issue by prettynatty** [websudos/phantom#163]
Because process looks like this:
```
bin/../resources/cassandra/bin/cqlsh
```
and `cassandraRunning` method only checks if cassandra is present in `ps` output.

**Comment by alexflav23** [comment]
@prettynatty This has now been fixed internally and the fix will go out in the next development release and in the next major release. Phantom will now attempt to actually connect to Cassandra instead of using any other checks and it will have specific consistent fail behaviour for known error types such as connection timeouts or invalid IPs. Please keep an eye out for the next release and everything should "just work" from there on.
