### ISSUE TITLE
Cassandra map with DateTime

### ISSUE THREAD

**Issue by lab3** [websudos/phantom#170]
I'm using a cassandra map <bigint, timestamp> 

import com.websudos.phantom.CassandraTable
import com.websudos.phantom.Implicits._

case class MyRow(
...
   last_answered: Map[Long, DateTime]
   )

class MyTable extends CassandraTable[MyTable, MyRow] {
...
  object last_answered extends MapColumn[RespondentAnswersTable, MyRow, Long, DateTime](this)
...
.
}

Getting a runtime exception for the map.

Column last_answered is a map of class java.lang.Long->class java.util.Date (CQL type map<bigint, timestamp>), cannot be retrieve as a map of class java.lang.Long->class org.joda.time.DateTime

**Comment by alexflav23** [comment]
@lab3 The discrepancy comes from the way we handle ```DateTime``` at DSL level, which is very basic to say the least. There is no explicit primitive of ```DateTime```, instead we use the ```java.util.Date``` support to cast back and forth. We will follow up on this and see where the wrong primitive is being called into action.

**Comment by alexflav23** [comment]
@lab3 This issue has finally been fixed in the primitive API and will be released in the next version. We've added tests to explicitly cover this scenario where the type of the collection you get out is not the type of the primitive used for extraction. It's just an internal concern that boiled up.

Thank you for reporting it, it certainly took a lot of change, including a new querybuilder, to address this among other things.
