### ISSUE TITLE
eqs not working

### ISSUE THREAD

**Issue by thiagoandrade6** [websudos/phantom#174]
I was trying to compare a java.util.UUID value to my sealed class who extends the Cassandra Table, a pretty standard feature of select and where clauses, but it gives me that eqs is not a member of object.

Whatever, I solved using a QueryCondition after looked up your code and it works fine.

Please, take a look at my [GIST](https://gist.github.com/thiagoandrade6/e715df01a5a04f81b649) for a better understand.

**Comment by alexflav23** [comment]
The only thing I can think of is that you're missing the correct important, respectively: ```import com.websudos.phantom.Implicits._```. This would be a pretty unpopular library without a working ```eqs```, as you can probably imagine. Please let me know if that fixes it.

**Comment by thiagoandrade6** [comment]
Yeah... it works! Thanks for your help again...
Importing the import com.websudos.phantom.Implicits._ solve the problem... I thought I was working with this, but was the scala implicits lol

**Comment by shaulzorea** [comment]
Hi @alexflav23,

Encountering the same issue while going through the [SimpleRecipes](https://github.com/outworkers/phantom/blob/develop/phantom-example/src/main/scala/com/websudos/phantom/example/basics/SimpleRecipes.scala) example.
I figure that you had changed the location of the implicits - since  `import com.websudos.phantom.Implicits._ ` is not recognised. I had added `import com.websudos.phantom.dsl._` but `eqs` still doesn't work.

Much appreciate your assistance, thanks.
