### ISSUE TITLE
Unresolved dependency for phantom zookeeper

### ISSUE THREAD

**Issue by arkady60** [websudos/phantom#196]
I am getting unresolved dependency for com.twitter#finagle-zookeeper_2.10;6.17.0
In build sbt i have included
"com.websudos" % "phantom-zookeeper_2.10" % "1.2.2"

and 
resolvers += "websudos-repo" at "http://maven.websudos.co.uk/ext-release-local"

resolvers += "twitter-repo" at "http://maven.twttr.com"

Please advice

**Comment by alexflav23** [comment]
@arkady60 Phantom 1.2.2 is no longer available publicly because of storage less in our Maven repository. The error has since been corrected and a 1.5.0 release of Phantom is available on Maven Central.

We advise you to upgrade to the newest available version as you will benefit from various bug fixes that have been included since 1.2.2 was released in August of 2014.
