### ISSUE TITLE
Remove zookeeper dependency

### ISSUE THREAD

**Issue by mstump** [websudos/phantom#221]
I'm having trouble understanding why you need a zookeeper dependency. The datastax driver will automatically load balance, and you shouldn't be doing anything new on thirft. Zookeeper is a single point  of shared mutable state with poor HA behavior, it's an anti-pattern for reliable distributed systems.

**Comment by alexflav23** [comment]
Hi @mstump,

The issue is indeed quite complex and not obvious, but the purpose of ZooKeeper is not to load balance or do any of the work the driver does. I think you are biased against ZooKeeper without seeing its concrete use, which doesn't have much to do with what you are describing.

The driver can indeed load balance, perform heartbeats, failovers and a lot of great staff, but it cannot be real-time aware to infrastructure events, such as new clusters being spawned into a system, failing nodes being replaced with new deployments with different ips and so forth. ZooKeeper does nothing but hold a collection of hosts and ports to which a series of applications write to, mainly tools like Chef and Puppet or Mesos/Aurora tasks which handle cluster management.

ZooKeeper is an optional dependency located in an isolated module which you don't even need to include unless you need it, and it sounds like you don't. It is perhaps worth taking the time to fully understand the issue before implying it should be removed as in a truly distributed environment you cannot really do anything without service discovery, be it ZooKeeper, etcd or whatever other tool.

Regards.

**Comment by mstump** [comment]
The datastax driver is topology aware you don't need to use ZK to be aware of existing nodes or new nodes being added to the cluster. I'm the author of the C++ driver, I'm intimately aware of the inner workings and protocol spec. ZK is an anti-pattern in any distributed HA system.

**Comment by alexflav23** [comment]
Hi @mstump,

Thank you for your feedback. In principle I don't disagree with anything you say, we use zookeeper to synchronise between virtual machines deployed in a cluster running in a Vagrant Box. Mesos + Apache Aurora can give you a local distributed environment.

ZooKeeper support wasn't built to make topology work, it was built to fit our specific needs as Mesos enforces ZooKeeper for that purpose and to sync with the whole lifecycle I don't think there is a way around it, at least not an easy way. Retrieving ports with a ZooKeeper client is absolutely trivial and the dependency has been long removed from newer versions.
