### ISSUE TITLE
Handling very large batch queries

### ISSUE THREAD

**Issue by polymorpher** [websudos/phantom#230]
*Update: this issue also seems to occur for smaller batch queries.*

I came across this type of error when I execute large batch queries:

2015-05-04 03:43:04,999 ERROR [pool-26-thread-1] phantom: line 1:1133150 mismatched character '<EOF>' expecting set null

Where the column number in "1:1133150" varies from time to time.

This particular query is an INSERT query consisting of some UUID columns, a Double column, a DateTime column, and a few text columns. The length of the text column could be very large (e.g a web article) but consists of only regular ASCII characters (32-126).

The total length of the query is 1686277. And column 1133150 is a character "l" (see below, enclosed by [])

"...punch heads don't a[l]ign well in 90..."

**Comment by polymorpher** [comment]
I switched back to 1.5.0. The problem disappeared. I believe there are some bugs in the new QueryBuilder

**Comment by alexflav23** [comment]
@polymorpher It is well possible we still have issues in the new builder, it's a very new and very large piece of work. Speed may even be impaired by the new "log by default" in debug mode, otherwise we will make sure to add more performance tests for batches although they are currently being tested already.

When you say by orders of magnitude faster what specifically are you referring to and how are you measuring?

**Comment by polymorpher** [comment]
I split around 10000-20000 queries into minibatches - with 1.5.0, 200+ mini batches completed in the blink of an eye, whereas with 1.8.1 I had to wait for much longer, the console output scrolls so slow so that I could leisurely observe the console output and the error messages : )

**Comment by alexflav23** [comment]
@polymorpher We've fixed the character escape problem. The batch size and performance issue is still being addresses, although the tests for it are still behaving relatively well. We have several of those and we have noticed a general performance improve in non-batched queries, but perhaps the alternation between batches and non-batches is not done properly.

It is a high priority item that will shortly be fixed.

**Comment by alexflav23** [comment]
Hi @polymorpher,

I've been trying to follow up on this as best as I could, but I'm having trouble replicating heavy performance issues outside of what I think could be a misunderstanding or misusage of the new API, possibly because we haven't made it obvious enough a crucial part of phantom has changed.

Back in the days of 1.5.0, calling `future` or `execute` on selects and batches would automatically use async iterators to execute tasks, which means that you have to explicitly call the iterator methods to benefit from optimised large queries. Otherwise, phantom won't be batching or lazy computing anything internally, so you end up with a big mess as you describe.

We have performance tests which ran during `perf:test` and no noticeable slow down or improvement in iterator performance has been done since the days of 1.0.0, since it was already more than anyone would ever need to use it for. 

If you put a Gist up, I can maybe help further, but I would first try explicitly using enumerators/iterators and see what happens.

Regards.

**Comment by polymorpher** [comment]
Thanks for helping out, Alex. I will give it a try in the next few days, using more rigorous testing procedure than I previously did.

**Comment by alexflav23** [comment]
Hi @polymorpher ,

We have reversed batch implementation to use the java driver and a lazy iterator based version instead of keeping a large generation string in memory. This has improved performance a lot. CQL now enforces a much smaller limitation for batch sizes though(Cassandra 2.2.0+) and we seem to be getting "Batch too large" errors even for 1000 queries, something to bear in mind when upgrading.

Phantom `1.12.2` will be out to Maven Central shorty and everything will be fixed.

Regards.
