### ISSUE TITLE
Tag releases properly

### ISSUE THREAD

**Issue by digital-wonderland** [websudos/phantom#238]
Hi,

could you please be so kind to tag releases properly (additionally uploading them to Github as release would be nice as well)? Apparently this happened earlier, until 1.4.0, but not anymore since then.

Reasoning is that it makes it much easier to figure out what code one is running - which is often quite helpful ;D. I.e. the latest release seems to be 1.8.4 but that version is nowhere mentioned in a commit message so I would have no idea what code I would need to debug stuff...

**Comment by alexflav23** [comment]
Hi @digital-wonderland,

We don't use GitHub for source control because it's poor PR mechanism along with many other things in less than ideal status. Now I'm wondering how often you debug library code in your applications given we haven't seen any contribution or fixes being pushed upstream and how much of a problem this really is on a wider scale to warrant us implementing the CI changes.

Regards,

**Comment by digital-wonderland** [comment]
Thanks for the quick response. I'm not using phantom yet but am evaluating it. Overall I like what I saw and my only pain points are missing support for prepared statements, which seems to be next on the todo list and the missing tags - which is why I opened this issue.

Regarding me debugging library code, well, every time something isn't working as expected :D Then being able to identify which commit I am running is kinda the prerequisite to submit any fixes or figuring out if that is already fixed in HEAD.

May I ask, what you use internally as version control? If it is Git as well, it shouldn't be much more than pushing things to a different remote (github) as well, not?

**Comment by alexflav23** [comment]
@digital-wonderland You are correct in assuming we still use Git, we will discuss this internally and get back to you shortly. It doesn't sound like a big change although I have to admit I'm rather weary of the benefits still.

**Comment by digital-wonderland** [comment]
sounds good, thanks a lot :)

**Comment by jknight12882** [comment]
Proper change logs and tagged releases are critical when evaluating when an upgrade is needed to a production system. I see that Bintray is now hosting 1.8.10, but I haven't seen any change logs showing what has been fixed/added since the initial 1.8.0 release.

**Comment by alexflav23** [comment]
Hi @jknight12882,

A changelog is available internally and it will be published to GitHub as soon as the release is publicly available on Maven Central. We don't use GitHub, it's just the front mirror, but we will endeavour to publish both a changelog and version tags.

Regards.

**Comment by alexflav23** [comment]
Hi @jknight12882 @digital-wonderland ,

This is the changelog for post 1.8.0 releases, the things I remember anyway. This was of the top of my head on this occasion and done somewhat impromptu, although we do promise to exercise greater discipline in the future regarding this practice.

Have a look at the [1.8.12 changelog](https://github.com/websudos/phantom/releases/tag/1.8.12) which details some of the changes done since `1.8.0` was released.

I will now close this issue as this will become standard practice.

Regards.
