### ISSUE TITLE
Scala API Documentation

### ISSUE THREAD

**Issue by willwest** [websudos/phantom#255]
Is there any generated scaladoc-style documentation of the phantom API? ([example](http://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/Row.html)) 

This would be a very nice addition to the existing documentation. While the docs in the README are relatively complete, a more technical, comprehensive description of the API would be helpful.

Is there a reason this hasn't been generated as of yet?

**Comment by alexflav23** [comment]
Hi @willwest,

Indeed this has been missing so far and it's a really good idea to publish it. We will discuss this internally and come up with a simple way to release this during the Travis CI phase.

Many thanks for your suggestion, it is indeed long overdue!

Regards,
Flavian

**Comment by willwest** [comment]
Sounds good, thanks Flavian!

**Comment by vyshane** [comment]
I second this. I would love to have this resource.

**Comment by sjohnc** [comment]
Has any progress been made on releasing this documentation?

**Comment by burann** [comment]
I second this, the API is probably good, but the amount time you have to waste to figure out simple thing is just mind boggling. I can appreciate the fact you want to build a consulting company on this, but if I cant effective evaluate the API, I wont get to a point where I will hire you either.

**Comment by alexflav23** [comment]
Hi @burann ,

We would appreciate some feedback on what people waste time on. The reason why this hasn't really been a focus is because the DSL is internally very complex, but very little of that complexity is exposed. So we will end up with a documentation that's far more bloated than what it should be, or at the very least that is the theory.

Phantom is designed to be discoverable via auto-completion, although we do realise that is not always possible and for that reason any feedback is welcome.

Regards.

**Comment by alexflav23** [comment]
Docs are now published [here](http://phantom-docs.s3-website-eu-west-1.amazonaws.com/#package).

**Comment by hsn10** [comment]
Can be this scaladoc updated?
