### ISSUE TITLE
Logic Error creating keyspace.columnfamily in queries

### ISSUE THREAD

**Issue by nosheenzaza** [websudos/phantom#272]
I am using phantom 1.8.4. I happened to create a keyspace with name recipes, and a table names recipes_main. When attempting to insert entries, I was getting the error "no keyspace has been specified" even when I was passing the keyspace explicitely. Debugging it seems the logic in method keyspace in file QueryBuilder is flawed:

```
  def keyspace(keySpace: String, qb: String): CQLQuery = {
    if (qb.startsWith(keySpace)) {
      CQLQuery(qb)
    }  else {
      CQLQuery(qb).prepend(s"$keySpace.")
    }
  }
```
Here because my column family name indeed starts with the keyspace name, the name of the keyspace is not appended even though it should. The code on Github is the same so I assume the problem exists in more recent versions as well. I doubt there is a rule against column family name not starting with the name of the database. Otherwise the logic needs to be fixed I believe.

**Comment by alexflav23** [comment]
Hi @nosheenzaza,

The logic is indeed flawed, there is no Cassandra restriction, simply a side effect of what at the time seemed trivial code. Upgrading to Phantom 1.9.5 will fix some other important bugs for you, so I do recommend that, but otherwise I will add the bug to the pipeline and a new release should be out very shortly to address this.

Regards.

**Comment by nosheenzaza** [comment]
Thank you for the quick response. I hope you consider again the request of #238 of tagging code with version numbers. I am modifying the phantom dsl for research purposes and it would be easier to have the code on Github.

**Comment by alexflav23** [comment]
Hi @nosheenzaza,

As you are aware, our license explicitly prohibits redistribution of phantom without our explicit consent. Phantom is free, usable as a library and so forth, however we don't allow custom versions, so anything that supports such things is not a priority for us, furthermore since GitHub is merely a mirror and we don't use it internally.

Regards.

**Comment by nosheenzaza** [comment]
I understand that and I do not intend to redistribute a custom version. I will contact you privately more for details.

**Comment by alexflav23** [comment]
Hi @nosheenzaza,

1.9.6 is now on Bintray and this issue has been fixed. It's not on Github yet but it is released.

Regards.

**Comment by nosheenzaza** [comment]
Perfect! Thank you very much.

**Comment by alexflav23** [comment]
Hi @nosheenzaza,

You will also start seeing tags appear, although they are the automatically generated tags created during release. If you are familiar with the Maven release lifecycle of `release -prepare` and `release perform`, we have something very similar for SBT.

The tags won't have any description per say whatsoever, but you could still diff between them.

Regards.

**Comment by nosheenzaza** [comment]
This is good enough. Thank you for that for bringing tags back.
