### ISSUE TITLE
Insert query serializing Error  

### ISSUE THREAD

**Issue by Kenzo777** [websudos/phantom#277]
Hi , 
I am trying to use insert query with  "IF NOT EXISTS" , "USING TTL 60 " 
SomeTable.insert
      .value(_.id, someId)
      .value(_.name, someName)
      .value(_.data,someData)
      .ifNotExists()
      .ttl(60)

I am getting error when executing this query  after debugging.  the query string built with wrong order 
INSERT  .................. USING TTL 60  IF NOT EXISTS  - which not legal in CQL  the correct query should be : INSERT  ..................  IF NOT EXISTS USING TTL 60  
can i override this in the code ? or maybe I am using the driver wrong , I am using 1.8.12

see reference here : http://docs.datastax.com/en/cql/3.1/cql/cql_reference/insert_r.html

thanks

**Comment by alexflav23** [comment]
Hi @Kenzo777,

This is indeed a problem on our end, I've added a ticket to the internal bug tracker and it will be dealt with probably this weekend, with a release following shortly after. I will keep you up-to-date.

Many thanks for reporting this, it is indeed quite strange that things are failing. I don't think the InsertQuery serialization order has changed since 1.8.12, however I would strongly advise you to upgrade to `1.9.8 ` to benefit from a plethora of other important bug fixes.

Regards.

**Comment by Kenzo777** [comment]
Thanks @alexflav23

**Comment by alexflav23** [comment]
Hi @Kenzo777,

This is fixed in `1.9.10` available on Bintray.

Regards.
