### ISSUE TITLE
Make Twitter libraries dependencies optional

### ISSUE THREAD

**Issue by Tvaroh** [websudos/phantom#282]
If one doesn't use Twitter's futures, it would be better to remove those artifacts from dependencies. Currently ignoring them doesn't work. Could chosen futures implementation be more pluggable?

**Comment by alexflav23** [comment]
Hi @Tvaroh ,

I don't think there is a good way around them, since the implementation is deeply embedded in Phantom. We only have 1 dependency on `util-core` from Twitter, but that is non-trivial and overall not very large in size.

We rarely use Scala primitives internally as they are in many many ways inferior to alternatives in the Twitter ecosystem. Is there any strong argument against Twitter futures otherwise?

**Comment by Tvaroh** [comment]
@alexflav23, thanks, I understand. I have nothing against Twitter futures, actually I never used them.
