### ISSUE TITLE
Java 8 time API support

### ISSUE THREAD

**Issue by Tvaroh** [websudos/phantom#283]
Currently, Phantom uses Joda time. Would be nice to have `java.time` API support as an additional module targeting Java 8, and also make Joda time deps optional.

@alexflav23, what do you think?

**Comment by alexflav23** [comment]
Hi @Tvaroh ,

This will likely be a lot of boilerplate for no reason and since not everyone is on Java 8 yet this is sightly dangerous. You can add a trivial conversion between Joda and Java dates and I highly doubt there would be a noticeable performance penalty in doing so.

It doesn't sound like this will be worth the trouble just yet.

Regards.

**Comment by Tvaroh** [comment]
I see, thanks.

**Comment by xpete** [comment]
joda.time could be set as deprecated and java.time support added only for java 1.8 users. It's a good change for a 2.0 version.

**Comment by mmatloka** [comment]
From a few versions there is a `phantom-jdk8` package with `java.time` columns.

**Comment by xpete** [comment]
Thanks
