### ISSUE TITLE
Q: Support of Consistancy Level ?

### ISSUE THREAD

**Issue by coffius** [websudos/phantom#290]
Is there support of setting of Consistancy Level for queries in phantom?
Right now I can not find a way to set CL for queries in phantom. I have tried to use `.consistencyLevel_=(ConsistencyLevel.LOCAL_QUORUM)` but it have led to errors like this:
```
ERROR: Internal Server Error with message line 1:94 missing EOF at 'USING' (...visitor_pixels WHERE visitor = 19e3ec00-2cad-11e5-8ba4-00497937b9bd [USING] CONSISTENCY...)
com.datastax.driver.core.exceptions.SyntaxError: line 1:94 missing EOF at 'USING' (...visitor_pixels WHERE visitor = 19e3ec00-2cad-11e5-8ba4-00497937b9bd [USING] CONSISTENCY...)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:101)
```

Is it possible to use some different methods to set CL?

**Comment by alexflav23** [comment]
Hi @coffius ,

Currently the consistency level in the latest versions of the CQL protocol is set in a whole new way, in a using clause. So you would have to execute two queries to effectively set the level of a query:

```scala

USE CONSISTENCY QUORUM;

UPDATE keyspace.table WHERE .. bla
```

This is somewhat misleading and a bit dangerous to do on the client because we would need to automatically batch queries and execute two things at once. There is also a problem is permanently having to reset the consistency level currently in use, in the event the "next" query does not have a consistency level set. So for every query, you would now have to run 3 queries, to set the consistency level, execute the actual query, and then unset it.

If you would use the Java driver, setting the consistency level produces the exact same query and having never set it in the first place, which means setting the level on a per query basis is no longer a possibility. We are very open to debate about this but our current understanding is that the level settings have indeed changed.
