### ISSUE TITLE
Maven Repo Version

### ISSUE THREAD

**Issue by Alien2150** [websudos/phantom#299]
Hey guys,

you mention in your Readme that you have the latest stable version in the official maven-repo (1.8.9) but its not there: 
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.websudos%22%20AND%20a%3A%22phantom_2.11%22 

It seems like that there is a version-difference between your own (https://dl.bintray.com/websudos/oss-releases/) and the official maven-repository.

Regards,
Thomas

**Comment by alexflav23** [comment]
Hi @Alien2150,

The readme also says you should rely on the badges at the top for the latest version because we do not generally update the docs as the same pace as internal releases. The latest version is `1.10.4` and there is also a version on Maven, `1.10.1`. They are of course different, since only larger releases wind up on Maven Central.

Hope this helps!
