### ISSUE TITLE
Twitter dependencies

### ISSUE THREAD

**Issue by jknight12882** [websudos/phantom#335]
Is it possible to separate out all the twitter dependencies into a separate project? Currently there's a lot of overhead requiring them as a dependency for those projects who don't rely on twitter futures/durations/etc

**Comment by alexflav23** [comment]
Hi @jknight12882,

We are very heavy users of Finagle internally and many of our products are built entirely on the Twitter stack. As a result, Scala concurrency support was added as a complementary choice to Twitter. We have yet to find a way in which support can be as painless and you are among the first to report the overhead, quite frankly the runtime overhead is 0, all you get is 15 more seconds of dependency resolution time.

We can accept pull requests but otherwise there this is probably not a high priority item as we see it, mainly as there are things like prepared statements to complete.

Regards.

**Comment by jknight12882** [comment]
@alexflav23 thanks for the quick response. The overhead is in distribution and developer convenience. 

For example, we use sbt-native-packager to distribute our app. As part of this, all dependencies are included as a "fat jar", so we are taking the overhead of having to include all those Twitter classes that are unused. 

As for developer convenience, we are heavy users of the standard Scala Future, so every time the IDE tries to autocomplete and import, it select the Twitter version first now (although this can be solved inside the IDE itself). 

Definitely not as high a priority as prepared statements, but I thought I'd throw it out there
