### ISSUE TITLE
QueryColumn has "eqs" but no "is"

### ISSUE THREAD

**Issue by dluwtw** [websudos/phantom#429]
`object userId extends UUIDColumn(this) with PartitionKey[UUID]
  object id extends TimeUUIDColumn(this) with PrimaryKey[UUID]`
.
.
.
```scala
def updateActivityFavorite(userId: UUID, activityFavorite: ActivityFavorite)(implicit ks: KeySpace): ConditionalQuery[ActivityFavoriteRecord, ActivityFavorite, _, _, _, _] =
    update
      .where(_.userId eqs userId)
      .and(_.id eqs activityFavorite.id)
      .modify(_.duration setTo activityFavorite.duration)
      .and(_.intensity setTo activityFavorite.intensity)
      .and(_.steps setTo activityFavorite.steps)
      .and(_.code setTo activityFavorite.code)
      .onlyIf(_.userId is userId)
```

Error:(52, 24) value is is not a member of object x$14.userId
      .onlyIf(_.userId is userId)
                       ^
Removing the last line compiles fine suggesting _id does have eqs so _id must be implicitly mapped to QueryColumn.

**Comment by alexflav23** [comment]
Hi,

Your update clause with an `is` is very pointless because you are already matching on the `userId`. CQL does not support a secondary condition(compare-and-set clauses) on columns that are part of the primary key of a table, which is why phantom doesn't let you compile them.

Doing that makes no sense whatsoever for a number of reasons: matching, breaching token distribution per partition, positioning in the ring via tokens, etc.

Regards.
